-- Initial schema. This service had no production database when migrations were introduced, so
-- V1 is simply the full schema as the Exposed tables in integrations/database/ declare it —
-- generated by `./gradlew generateMigrationScript`, not hand-written. MigrationSchemaTest keeps
-- the two in step.
--
-- `created_at`/`updated_at` are DATETIME(6) with no DEFAULT on purpose: the application always
-- writes them itself from the injected Clock (OurInfoGatewayImpl), never relying on the server.

CREATE TABLE IF NOT EXISTS label (id INT AUTO_INCREMENT PRIMARY KEY, canonical_name VARCHAR(255) NOT NULL, created_at DATETIME(6) NOT NULL);
ALTER TABLE label ADD CONSTRAINT label_canonical_name_unique UNIQUE (canonical_name);
CREATE TABLE IF NOT EXISTS label_copyright (id INT AUTO_INCREMENT PRIMARY KEY, label_id INT NOT NULL, copyright_text VARCHAR(255) NOT NULL, created_at DATETIME(6) NOT NULL, CONSTRAINT fk_label_copyright_label_id__id FOREIGN KEY (label_id) REFERENCES label(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
ALTER TABLE label_copyright ADD CONSTRAINT label_copyright_label_id_copyright_text_unique UNIQUE (label_id, copyright_text);
CREATE TABLE IF NOT EXISTS track (id INT AUTO_INCREMENT PRIMARY KEY, spotify_id VARCHAR(64) NOT NULL, isrc VARCHAR(32) NOT NULL, `name` VARCHAR(255) NOT NULL, created_at DATETIME(6) NOT NULL);
ALTER TABLE track ADD CONSTRAINT track_spotify_id_unique UNIQUE (spotify_id);
ALTER TABLE track ADD CONSTRAINT track_isrc_unique UNIQUE (isrc);
CREATE TABLE IF NOT EXISTS label_track (label_id INT, track_id INT, created_at DATETIME(6) NOT NULL, CONSTRAINT pk_label_track PRIMARY KEY (label_id, track_id), CONSTRAINT fk_label_track_label_id__id FOREIGN KEY (label_id) REFERENCES label(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_label_track_track_id__id FOREIGN KEY (track_id) REFERENCES track(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS spotify_account (id INT AUTO_INCREMENT PRIMARY KEY, spotify_user_id VARCHAR(64) NOT NULL, refresh_token VARCHAR(512) NOT NULL, scopes VARCHAR(255) NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL);
ALTER TABLE spotify_account ADD CONSTRAINT spotify_account_spotify_user_id_unique UNIQUE (spotify_user_id);
